#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "picknik_ur_gazebo_config"

hardware:
  # Used by the ur_description package to set kinematics and geometry for a specific robot type.
  type: "ur10e"

  simulated_hardware_launch_file:
    package: "ur10e_gazebo_scan_and_plan_config"
    path: "launch/sim/hardware_sim.launch.py"

  # because we are using the picknik_ur_gazebo_config as the base package we need a custom srdf that matches the ur10 robot
  robot_description:
    srdf:
      package: "ur10e_gazebo_scan_and_plan_config"
      path: "config/moveit/ur_gazebo.srdf.xacro"

# Optional parameters that can be read in your launch files for specific functionality
optional_feature_params:
  gazebo_world_package_name: "ur10e_gazebo_scan_and_plan_config"
  gazebo_world_path: "description/simulation_worlds/scan_and_plan_world.sdf"

objectives:
  behavior_loader_plugins:
    april_tag:
      - "get_apriltag_detection_pose::GetApriltagDetectionPoseBehaviorsLoader"
  # Override with a new set of waypoints based on the Gazebo world.
  waypoints_file:
    package_name: "ur10e_scan_config"
    relative_path: "waypoints/waypoints.yaml"
  # Add new scan and plan Objectives in addition to the one in the base config package.
  objective_library_paths:
    scan:
      package_name: "ur10e_scan_config"
      relative_path: "objectives"
