###############################################################
#
#  This configures the robot to work with moveit studio
#
###############################################################

hardware:
  # Used by the ur_description package to set kinematics and geometry for a specific robot type.
  type: "ur10e"
  simulated: ${MOCK_HARDWARE:-true}

  # If MoveIt Studio should launch the ros2 controller node
  launch_control_node: True

  # If MoveIt Studio should launch the robot state publisher
  launch_robot_state_publisher: True

  # If MoveIt Studio should launch cameras when simulated
  launch_cameras_when_simulated: False

  # The robot's IP address
  ip: 169.254.121.40

  robot_driver_persist_launch_file:
    package: "ur10e_scan_config"
    path: "launch/robot_drivers_to_persist.launch.py"
  robot_driver_restart_launch_file:
    package: "ur10e_scan_config"
    path: "launch/robot_drivers_to_restart.launch.py"
  hardware_launch_file:
    package: "ur10e_scan_config"
    path: "launch/hardware.launch.py"

  simulated_robot_driver_persist_launch_file:
    package: "ur10e_scan_config"
    path: "launch/sim/robot_drivers_to_persist_sim.launch.py"
  simulated_robot_driver_restart_launch_file:
    package: "ur10e_scan_config"
    path: "launch/sim/robot_drivers_to_restart_sim.launch.py"
  simulated_hardware_launch_file:
    package: "ur10e_scan_config"
    path: "launch/sim/hardware_sim.launch.py"

  camera_config_file:
    package: "ur10e_scan_config"
    path: "config/cameras.yaml"

  # Parameters used to configure the robot description through XACRO
  robot_description:
    urdf:
      package: "ur10e_scan_config"
      path: "description/ur10e_scan.xacro"
    srdf:
      package: "ur10e_scan_config"
      path: "config/moveit/ur10e_scan.srdf"
    urdf_params:
      - name: "%>> hardware.type"
      - tf_prefix: ""
      - use_sim: "%>> hardware.simulated"
      - use_fake_hardware: "%>> hardware.simulated"
      - mock_sensor_commands: "false"
      - headless_mode: "true"
      - robot_ip: "%>> hardware.ip"
      - external_camera: "%>> hardware.simulated"  # set to match sim status to support prior sim behavior
      - joint_limits_parameters_file:
          package: "ur10e_scan_config"
          path: "config/moveit/joint_limits.yaml"
      - kinematics_parameters_file:
          package: "ur_description"
          path: "config/%>> hardware.type <<%/default_kinematics.yaml"
      - physical_parameters_file:
          package: "ur_description"
          path: "config/%>> hardware.type <<%/physical_parameters.yaml"
      - visual_parameters_file:
          package: "ur_description"
          path: "config/%>> hardware.type <<%/visual_parameters.yaml"

ros_global_params:
  use_sim_time: False

optional_feature_params:
  use_joystick: False
  use_external_webcam: False
  use_formant_bridge: False

# This Configures moveit params that are in moveit_config.py
moveit_params:
  joint_group_name: "manipulator"

  ompl_planning:
    package: "ur10e_scan_config"
    path: "config/moveit/ompl_planning.yaml"
  stomp_planning:
    package: "ur10e_scan_config"
    path: "config/moveit/stomp_planning.yaml"
  kinematics:
    package: "ur10e_scan_config"
    path: "config/moveit/trac_ik_kinematics.yaml"
  servo:
    package: "ur10e_scan_config"
    path: "config/moveit/ur10e_servo.yaml"
  sensors_3d:
    package: "ur10e_scan_config"
    path: "config/moveit/sensors_3d.yaml"
  servo_kinematics:
    package: "ur10e_scan_config"
    path: "config/moveit/trac_ik_kinematics.yaml"
  joint_limits:
    package: "ur10e_scan_config"
    path: "config/moveit/joint_limits.yaml"
  pilz_cartesian_limits:
    package: "ur10e_scan_config"
    path: "config/moveit/pilz_cartesian_limits.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

ui_params:
  servo_endpoint_frame_id: "manual_grasp_link"

# This configures what controllers gets run at startup
ros2_control:
  config:
    package: "ur10e_scan_config"
    path: "config/control/ur10e.ros2_control.yaml"
  # Load and start these controllers so they can be used immediately.
  controllers_active_at_startup:
    - "force_torque_sensor_broadcaster"
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
    - "io_and_status_controller"
    - "robotiq_activation_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  controllers_inactive_at_startup:
    - "streaming_controller"
    - "admittance_controller"
    - "chained_joint_trajectory_controller"
  # Configure remapping rules to let multiple controllers receive commands on the same topic.
  controller_shared_topics:
    "/robot_controllers/commands":
      - "/streaming_controller/commands"
    "/robot_controllers/joint_trajectory":
      - "/joint_trajectory_controller/joint_trajectory"
      - "/chained_joint_trajectory_controller/joint_trajectory"

# Octomap manager configuration parameters
octomap_manager:
  # Input point cloud topic name. The *output* point cloud topic published by
  # the Octomap manager node is defined in sensors_3d.yaml.
  input_point_cloud_topic: "/wrist_mounted_camera/depth/color/points"

objectives:
  behavior_loader_plugins:
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
    my_behaviors:
      - "transform_print_pose::TransformPrintPoseBehaviorsLoader"
  objective_library_paths:
    core:
      package_name: "ur10e_scan_config"
      relative_path: "objectives"
  waypoints_file:
    package_name: "ur10e_scan_config"
    relative_path: "waypoints/waypoints.yaml"
